/* eslint-disable max-len */
import { Comic } from '../../../interfaces/comic';

export const mockedComics: Comic[] = [
  {
    id: 94227,
    digitalId: 0,
    title: 'Giant-Size Amazing Spider-Man: Chameleon Conspiracy (2021) #1',
    issueNumber: 1,
    variantDescription: '',
    description: null,
    modified: '2021-06-28T12:03:58-0400',
    isbn: '',
    upc: '75960620158700111',
    diamondCode: 'APR210890',
    ean: '',
    issn: '',
    format: 'Comic',
    pageCount: 56,
    textObjects: [],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/94227',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/issue/94227/giant-size_amazing_spider-man_chameleon_conspiracy_2021_1?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/GIANT-SIZE-AMAZING-SPIDER-MAN-CHAMELEON-CONSPIRACY-1-1/digital-comic/56986?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: {
      resourceURI: 'http://gateway.marvel.com/v1/public/series/32137',
      name: 'Giant-Size Amazing Spider-Man: Chameleon Conspiracy (2021)',
    },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2021-06-30T00:00:00-0400' },
      { type: 'focDate', date: '2021-06-07T00:00:00-0400' },
    ],
    prices: [{ type: 'printPrice', price: 5.99 }],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/4/e0/609ed79d86865', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/4/e0/609ed79d86865', extension: 'jpg' }],
    creators: {
      available: 16,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/94227/creators',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/87',
          name: 'Mark Bagley',
          role: 'penciler (cover)',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12699', name: 'Ed Brisson', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/11434', name: 'Nick Spencer', role: 'writer' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/5251',
          name: 'Vc Joe Caramagna',
          role: 'letterer',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13898', name: 'Ze Carlos', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/359', name: 'John Dell', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/544', name: 'Wayne Faucher', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/10355', name: 'Carlos Gomez', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/8606', name: 'Ig Guara', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/8028', name: 'Andrew Crossley', role: 'colorist' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/774', name: 'Morry Hollowell', role: 'colorist' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/12991',
          name: 'Rachelle Rosenberg',
          role: 'colorist',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/13604',
          name: 'Marcelo Ferreira',
          role: 'penciler',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/548',
          name: 'Andrew Hennessy',
          role: 'inker (cover)',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/4300', name: 'Nick Lowe', role: 'editor' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/582',
          name: 'Brian Reber',
          role: 'colorist (cover)',
        },
      ],
      returned: 16,
    },
    characters: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/94227/characters',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009234', name: 'Chameleon' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009610', name: 'Spider-Man' },
      ],
      returned: 2,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/94227/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/209572',
          name: 'cover from Giant-Size Amazing Spider-Man: Chameleon Conspiracy (2021) #1',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/209573',
          name: 'story from Giant-Size Amazing Spider-Man: Chameleon Conspiracy (2021) #1',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/94227/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 95100,
    digitalId: 0,
    title: 'Black Cat Annual (2021) #1',
    issueNumber: 1,
    variantDescription: '',
    description: null,
    modified: '2021-06-28T12:02:53-0400',
    isbn: '',
    upc: '759606201861000111',
    diamondCode: 'APR210738',
    ean: '',
    issn: '',
    format: 'Comic',
    pageCount: 40,
    textObjects: [],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/95100',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/issue/95100/black_cat_annual_2021_1?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/BLACK-CAT-ANNUAL-1-1/digital-comic/56982?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: { resourceURI: 'http://gateway.marvel.com/v1/public/series/32384', name: 'Black Cat Annual (2021)' },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2021-06-30T00:00:00-0400' },
      { type: 'focDate', date: '2021-06-07T00:00:00-0400' },
    ],
    prices: [{ type: 'printPrice', price: 4.99 }],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/7/70/609ece289b399', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/7/70/609ece289b399', extension: 'jpg' }],
    creators: {
      available: 8,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/95100/creators',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/5251',
          name: 'Vc Joe Caramagna',
          role: 'letterer',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12985', name: 'Ferran Delgado', role: 'letterer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13558', name: 'Juan Ferreyra', role: 'colorist' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/4300', name: 'Nick Lowe', role: 'editor' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13471', name: 'Jed Mackay', role: 'writer' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/582',
          name: 'Brian Reber',
          role: 'colorist (cover)',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13494', name: 'Joey Vazquez', role: 'penciler' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/13276',
          name: 'C.F. Villa',
          role: 'inker (cover)',
        },
      ],
      returned: 8,
    },
    characters: {
      available: 1,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/95100/characters',
      items: [{ resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009185', name: 'Black Cat' }],
      returned: 1,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/95100/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/211328',
          name: 'cover from Black Cat Annual (2021) #1',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/211329',
          name: 'story from Black Cat Annual (2021) #1',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/95100/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 92203,
    digitalId: 0,
    title: 'Black Panther (2021) #1',
    issueNumber: 1,
    variantDescription: '',
    description: null,
    modified: '2021-06-26T09:02:53-0400',
    isbn: '',
    upc: '75960620042900111',
    diamondCode: 'JUN210517',
    ean: '',
    issn: '',
    format: 'Comic',
    pageCount: 40,
    textObjects: [],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/92203',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/issue/92203/black_panther_2021_1?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: { resourceURI: 'http://gateway.marvel.com/v1/public/series/31553', name: 'Black Panther (2021 - Present)' },
    variants: [
      { resourceURI: 'http://gateway.marvel.com/v1/public/comics/95985', name: 'Black Panther (2021) #1 (Variant)' },
      { resourceURI: 'http://gateway.marvel.com/v1/public/comics/95983', name: 'Black Panther (2021) #1 (Variant)' },
    ],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2021-08-04T00:00:00-0400' },
      { type: 'focDate', date: '2021-07-12T00:00:00-0400' },
    ],
    prices: [{ type: 'printPrice', price: 4.99 }],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/7/30/60da36b898c79', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/7/30/60da36b898c79', extension: 'jpg' }],
    creators: {
      available: 6,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92203/creators',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13180', name: 'Federico Blee', role: 'colorist' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13031', name: 'Juann Cabal', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12376', name: 'Wilson Moss', role: 'editor' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/14138', name: 'John Ridley', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/63', name: 'Alex Ross', role: 'painter (cover)' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12974', name: 'Vc Joe Sabino', role: 'letterer' },
      ],
      returned: 6,
    },
    characters: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92203/characters',
      items: [],
      returned: 0,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92203/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/205490',
          name: 'cover from Black Panther (2021) #1',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/205491',
          name: 'story from Black Panther (2021) #1',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92203/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 84307,
    digitalId: 0,
    title: 'U.S.Agent: American Zealot (Trade Paperback)',
    issueNumber: 0,
    variantDescription: '',
    description: null,
    modified: '2021-06-25T09:55:56-0400',
    isbn: '978-1-302-92476-8',
    upc: '',
    diamondCode: 'APR210995',
    ean: '9781302 924768 51599',
    issn: '',
    format: 'Trade Paperback',
    pageCount: 112,
    textObjects: [],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/84307',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/collection/84307/usagent_american_zealot_trade_paperback?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/U-S-Agent-American-Zealot-0/digital-comic/56946?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: {
      resourceURI: 'http://gateway.marvel.com/v1/public/series/29681',
      name: 'U.S.Agent: American Zealot (2021)',
    },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2021-06-23T00:00:00-0400' },
      { type: 'focDate', date: '2021-05-03T00:00:00-0400' },
    ],
    prices: [{ type: 'printPrice', price: 15.99 }],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/6/60/60d355819ac6b', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/6/60/60d355819ac6b', extension: 'jpg' }],
    creators: {
      available: 4,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/84307/creators',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/11748',
          name: 'Marco Checchetto',
          role: 'penciller (cover)',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/188', name: 'Georges Jeanty', role: 'penciller' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/110', name: 'Christopher Priest', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/4430', name: 'Jeff Youngquist', role: 'editor' },
      ],
      returned: 4,
    },
    characters: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/84307/characters',
      items: [],
      returned: 0,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/84307/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/186402',
          name: 'cover from U.S.AGENT TPB (2021) #1',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/186403',
          name: 'story from U.S.AGENT TPB (2021) #1',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/84307/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 80534,
    digitalId: 0,
    title: 'Star Wars: Darth Vader By Greg Pak Vol. 2 - Into The Fire (Trade Paperback)',
    issueNumber: 0,
    variantDescription: '',
    description: null,
    modified: '2021-06-25T09:54:29-0400',
    isbn: '978-1-302-92082-1',
    upc: '',
    diamondCode: 'MAR210704',
    ean: '9781302 920821 51799',
    issn: '',
    format: 'Trade Paperback',
    pageCount: 136,
    textObjects: [],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/80534',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/collection/80534/star_wars_darth_vader_by_greg_pak_vol_2_-_into_the_fire_trade_paperback?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/Star-Wars-Darth-Vader-By-Greg-Pak-Vol-2-Into-The-Fire-0/digital-comic/56943?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: {
      resourceURI: 'http://gateway.marvel.com/v1/public/series/28378',
      name: 'Star Wars: Darth Vader By Greg Pak Vol. 2 - Into The Fire (2021)',
    },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2021-06-23T00:00:00-0400' },
      { type: 'focDate', date: '2021-04-19T00:00:00-0400' },
    ],
    prices: [{ type: 'printPrice', price: 17.99 }],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/4/03/60d35570817b3', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/4/03/60d35570817b3', extension: 'jpg' }],
    creators: {
      available: 1,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/80534/creators',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/4430', name: 'Jeff Youngquist', role: 'editor' },
      ],
      returned: 1,
    },
    characters: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/80534/characters',
      items: [],
      returned: 0,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/80534/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/178192',
          name: 'cover from STAR WARS: DARTH VADER VOL. 2 TPB (2021) #2',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/178193',
          name: 'story from STAR WARS: DARTH VADER VOL. 2 TPB (2021) #2',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/80534/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 93818,
    digitalId: 0,
    title: 'Star Wars Legends Epic Collection: The Old Republic Vol. 4 (Trade Paperback)',
    issueNumber: 0,
    variantDescription: '',
    description: null,
    modified: '2021-06-25T09:52:24-0400',
    isbn: '978-1-302-93087-5',
    upc: '',
    diamondCode: 'MAR210716',
    ean: '9781302 930875 53999',
    issn: '',
    format: 'Trade Paperback',
    pageCount: 456,
    textObjects: [],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/93818',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/collection/93818/star_wars_legends_epic_collection_the_old_republic_vol_4_trade_paperback?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/Star-Wars-Legends-Epic-Collection-The-Old-Republic-Vol-4-0/digital-comic/56855?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: {
      resourceURI: 'http://gateway.marvel.com/v1/public/series/32053',
      name: 'Star Wars Legends Epic Collection: The Old Republic Vol. 4 (2021)',
    },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2021-06-23T00:00:00-0400' },
      { type: 'focDate', date: '2021-04-05T00:00:00-0400' },
    ],
    prices: [{ type: 'printPrice', price: 39.99 }],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/d/30/60d3557080660', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/d/30/60d3557080660', extension: 'jpg' }],
    creators: {
      available: 18,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/93818/creators',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/498', name: 'Greg Adams', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/558', name: 'Mark Mckenna', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/741', name: 'Alex Sanchez', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/767', name: 'Michael Atiyeh', role: 'colorist' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/10783', name: 'John Rauch', role: 'colorist' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/14245', name: 'Rob Chestney', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12657', name: 'Alexander Freed', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12540', name: 'Adam Gallardo', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12537', name: 'Mike Hansen', role: 'writer' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/13474',
          name: 'John Jackson Miller',
          role: 'writer',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13100', name: 'Jeph York', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/1928', name: 'Steve Dutro', role: 'letterer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/1892', name: 'Michael Heisler', role: 'letterer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/5816', name: 'George Freeman', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/10119', name: 'Andrea Mutti', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/5022', name: 'David Nakayama', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12538', name: 'Dave Ross', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/4430', name: 'Jeff Youngquist', role: 'editor' },
      ],
      returned: 18,
    },
    characters: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/93818/characters',
      items: [],
      returned: 0,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/93818/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/208751',
          name: 'cover from STAR WARS LEGENDS EPIC COLLECTION: THE OLD REPUBLIC VOL. 4 TPB (2021) #4',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/208752',
          name: 'story from STAR WARS LEGENDS EPIC COLLECTION: THE OLD REPUBLIC VOL. 4 TPB (2021) #4',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/93818/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 93145,
    digitalId: 0,
    title: 'Silk: Out Of The Spider-Verse Vol. 2  (Trade Paperback)',
    issueNumber: 0,
    variantDescription: '',
    description: null,
    modified: '2021-06-25T09:50:55-0400',
    isbn: '978-1-302-92988-6',
    upc: '',
    diamondCode: 'APR211003',
    ean: '9781302 929886 53499',
    issn: '',
    format: 'Trade Paperback',
    pageCount: 336,
    textObjects: [],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/93145',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/collection/93145/silk_out_of_the_spider-verse_vol_2_trade_paperback?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/Silk-Out-Of-The-Spider-Verse-Vol-2-0/digital-comic/56941?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: {
      resourceURI: 'http://gateway.marvel.com/v1/public/series/31858',
      name: 'Silk: Out Of The Spider-Verse Vol. 2  (2021)',
    },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2021-06-23T00:00:00-0400' },
      { type: 'focDate', date: '2021-05-03T00:00:00-0400' },
    ],
    prices: [{ type: 'printPrice', price: 34.99 }],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/d/70/60d3557076722', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/d/70/60d3557076722', extension: 'jpg' }],
    creators: {
      available: 1,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/93145/creators',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/4430', name: 'Jeff Youngquist', role: 'editor' },
      ],
      returned: 1,
    },
    characters: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/93145/characters',
      items: [],
      returned: 0,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/93145/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/207402',
          name: 'cover from SILK: OUT OF THE SPIDER-VERSE VOL. 2 TPB (2021) #2',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/207403',
          name: 'story from SILK: OUT OF THE SPIDER-VERSE VOL. 2 TPB (2021) #2',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/93145/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 93140,
    digitalId: 0,
    title: 'Miles Morales: Ultimate End (Trade Paperback)',
    issueNumber: 0,
    variantDescription: '',
    description: null,
    modified: '2021-06-25T09:48:52-0400',
    isbn: '978-1-302-92983-1',
    upc: '',
    diamondCode: 'MAR210718',
    ean: '9781302 929831 51299',
    issn: '2377-0066',
    format: 'Trade Paperback',
    pageCount: 272,
    textObjects: [],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/93140',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/collection/93140/miles_morales_ultimate_end_trade_paperback?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/Miles-Morales-Ultimate-End-0/digital-comic/56937?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: {
      resourceURI: 'http://gateway.marvel.com/v1/public/series/31853',
      name: 'Miles Morales: Ultimate End (2021)',
    },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2021-06-23T00:00:00-0400' },
      { type: 'focDate', date: '2021-04-12T00:00:00-0400' },
    ],
    prices: [{ type: 'printPrice', price: 12.99 }],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/3/90/60d355707e45e', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/3/90/60d355707e45e', extension: 'jpg' }],
    creators: {
      available: 6,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/93140/creators',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/24',
          name: 'Brian Michael Bendis',
          role: 'writer',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/426', name: 'Jason Keith', role: 'colorist' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/360', name: 'Justin Ponsor', role: 'colorist' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/11610', name: 'David Marquez', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12980', name: 'Vc Cory Petit', role: 'letterer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/4430', name: 'Jeff Youngquist', role: 'editor' },
      ],
      returned: 6,
    },
    characters: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/93140/characters',
      items: [],
      returned: 0,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/93140/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/207392',
          name: 'cover from MILES MORALES: ULTIMATE END GN-TPB (2021) #1',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/207393',
          name: 'story from MILES MORALES: ULTIMATE END GN-TPB (2021) #1',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/93140/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 30122,
    digitalId: 19925,
    title: 'Marvel Adventures Super Heroes (2010) #12',
    issueNumber: 12,
    variantDescription: '',
    description:
      'Bruce Banner confronts the Abomination in the deserts of New Mexico. Only, it’s the Hulk who shows up for the fight!',
    modified: '2021-06-23T17:17:49-0400',
    isbn: '',
    upc: '75960607126501211',
    diamondCode: 'JAN110738',
    ean: '',
    issn: '1938-0380',
    format: 'Comic',
    pageCount: 32,
    textObjects: [
      {
        type: 'issue_solicit_text',
        language: 'en-us',
        text: 'Bruce Banner confronts the Abomination in the deserts of New Mexico. Only, it’s the Hulk who shows up for the fight!',
      },
    ],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/30122',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/issue/30122/marvel_adventures_super_heroes_2010_12?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'reader',
        url: 'http://marvel.com/digitalcomics/view.htm?iid=19925&utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: {
      resourceURI: 'http://gateway.marvel.com/v1/public/series/9718',
      name: 'Marvel Adventures Super Heroes (2010 - 2012)',
    },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2011-03-09T00:00:00-0500' },
      { type: 'focDate', date: '-0001-11-30T00:00:00-0500' },
      { type: 'unlimitedDate', date: '2012-12-20T00:00:00-0500' },
    ],
    prices: [{ type: 'printPrice', price: 2.99 }],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/2/c0/60d249d1a1731', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/2/c0/60d249d1a1731', extension: 'jpg' }],
    creators: {
      available: 4,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/30122/creators',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/1189', name: 'Ryan Odagawa', role: 'penciller' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/684', name: 'Mike Raicht', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/10783', name: 'John Rauch', role: 'colorist' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/8429', name: 'Dave Sharpe', role: 'letterer' },
      ],
      returned: 4,
    },
    characters: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/30122/characters',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009351', name: 'Hulk' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009664', name: 'Thor' },
      ],
      returned: 2,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/30122/stories',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/stories/69070', name: 'SUPER HEROES 12', type: 'cover' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/69071',
          name: 'SUPER HEROES 12 ',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/30122/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 92791,
    digitalId: 56408,
    title: 'King In Black: Scream (2021) #1',
    issueNumber: 1,
    variantDescription: '',
    description: null,
    modified: '2021-06-23T13:45:33-0400',
    isbn: '',
    upc: '75960620080100111',
    diamondCode: 'JAN210537',
    ean: '',
    issn: '',
    format: 'Comic',
    pageCount: 40,
    textObjects: [],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/92791',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/issue/92791/king_in_black_scream_2021_1?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/King-In-Black-Scream-1/digital-comic/56408?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'reader',
        url: 'http://marvel.com/digitalcomics/view.htm?iid=56408&utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'inAppLink',
        url: 'https://applink.marvel.com/issue/56408?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: {
      resourceURI: 'http://gateway.marvel.com/v1/public/series/31706',
      name: 'King In Black: Scream (2021 - Present)',
    },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2021-03-24T00:00:00-0400' },
      { type: 'focDate', date: '2021-03-01T00:00:00-0500' },
      { type: 'unlimitedDate', date: '2021-06-28T00:00:00-0400' },
      { type: 'digitalPurchaseDate', date: '2021-03-24T00:00:00-0400' },
    ],
    prices: [
      { type: 'printPrice', price: 4.99 },
      { type: 'digitalPurchasePrice', price: 4.99 },
    ],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/9/40/605cee6242ea7', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/9/40/605cee6242ea7', extension: 'jpg' }],
    creators: {
      available: 5,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92791/creators',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12422', name: 'Garry Brown', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13137', name: 'Clay Chapman', role: 'writer' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/13138',
          name: 'In-Hyuk Lee',
          role: 'painter (cover)',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/12457',
          name: 'Edward Devin Lewis',
          role: 'editor',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12980', name: 'Vc Cory Petit', role: 'letterer' },
      ],
      returned: 5,
    },
    characters: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92791/characters',
      items: [],
      returned: 0,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92791/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/206681',
          name: 'cover from King in Black: Scream (2021) #1',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/206682',
          name: 'story from King in Black: Scream (2021) #1',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92791/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 91809,
    digitalId: 0,
    title: 'King In Black: Return Of The Valkyries (Trade Paperback)',
    issueNumber: 0,
    variantDescription: '',
    description: null,
    modified: '2021-06-23T12:26:52-0400',
    isbn: '978-1-302-92808-7',
    upc: '',
    diamondCode: 'MAR210702',
    ean: '9781302 928087 51599',
    issn: '',
    format: 'Trade Paperback',
    pageCount: 112,
    textObjects: [],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/91809',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/collection/91809/king_in_black_return_of_the_valkyries_trade_paperback?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/King-In-Black-Return-Of-The-Valkyries-0/digital-comic/56845?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: {
      resourceURI: 'http://gateway.marvel.com/v1/public/series/31404',
      name: 'King In Black: Return Of The Valkyries (2021)',
    },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2021-06-23T00:00:00-0400' },
      { type: 'focDate', date: '2021-04-05T00:00:00-0400' },
    ],
    prices: [{ type: 'printPrice', price: 15.99 }],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/3/70/60d355707c72e', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/3/70/60d355707c72e', extension: 'jpg' }],
    creators: {
      available: 6,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/91809/creators',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/11463', name: 'Jason Aaron', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/14017', name: 'Torunn Gronbekk', role: 'writer' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/12744',
          name: 'Tamra Bonvillain',
          role: 'colorist',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12974', name: 'Vc Joe Sabino', role: 'letterer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13606', name: 'Nina Vakueva', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/4430', name: 'Jeff Youngquist', role: 'editor' },
      ],
      returned: 6,
    },
    characters: {
      available: 1,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/91809/characters',
      items: [{ resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010329', name: 'Jane Foster' }],
      returned: 1,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/91809/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/204703',
          name: 'cover from VALKYRIES TPB (2021) #1',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/204704',
          name: 'story from VALKYRIES TPB (2021) #1',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/91809/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 36736,
    digitalId: 20464,
    title: 'Marvel Adventures Super Heroes (2010) #13',
    issueNumber: 13,
    variantDescription: '',
    description:
      "Spotlighting Marvel's newest movie star, Thor! When the Thunder God and Valkyrie plunge into the Asgardian afterworld, why do they bring along Nova?! What is the dreadful mission, and will even the combined might of Thor and Valkyrie and Nova be enough to complete it?",
    modified: '2021-06-23T12:09:26-0400',
    isbn: '',
    upc: '5960607126-01311',
    diamondCode: 'FEB110569',
    ean: '',
    issn: '1938-0380',
    format: 'Comic',
    pageCount: 32,
    textObjects: [
      {
        type: 'issue_solicit_text',
        language: 'en-us',
        text: "Spotlighting Marvel's newest movie star, Thor! When the Thunder God and Valkyrie plunge into the Asgardian afterworld, why do they bring along Nova?! What is the dreadful mission, and will even the combined might of Thor and Valkyrie and Nova be enough to complete it?",
      },
    ],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/36736',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/issue/36736/marvel_adventures_super_heroes_2010_13?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'reader',
        url: 'http://marvel.com/digitalcomics/view.htm?iid=20464&utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: {
      resourceURI: 'http://gateway.marvel.com/v1/public/series/9718',
      name: 'Marvel Adventures Super Heroes (2010 - 2012)',
    },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2011-04-13T00:00:00-0400' },
      { type: 'focDate', date: '2011-03-21T00:00:00-0400' },
      { type: 'unlimitedDate', date: '2011-12-12T00:00:00-0500' },
    ],
    prices: [{ type: 'printPrice', price: 2.99 }],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/3/30/60d249d1a1774', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/3/30/60d249d1a1774', extension: 'jpg' }],
    creators: {
      available: 7,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/36736/creators',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12401', name: 'Sotocolor', role: 'colorist' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/665',
          name: 'Reilly Brown',
          role: 'penciller (cover)',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/1430', name: 'Ronan Cliquet', role: 'penciller' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/5139', name: 'Amilton Santos', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/8429', name: 'Dave Sharpe', role: 'letterer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/4983', name: 'Paul Tobin', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/11879', name: 'Stephen Wacker', role: 'editor' },
      ],
      returned: 7,
    },
    characters: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/36736/characters',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009477', name: 'Nova' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009664', name: 'Thor' },
      ],
      returned: 2,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/36736/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/81472',
          name: 'Marvel Adventures Super Heroes (2010) #13',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/81473',
          name: 'Marvel Adventures Super Heroes (2010) #13',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/36736/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 47771,
    digitalId: 0,
    title: 'Journey Into Mystery by Kieron Gillen: The Complete Collection (Trade Paperback)',
    issueNumber: 1,
    variantDescription: '',
    description: null,
    modified: '2021-06-23T11:41:19-0400',
    isbn: '978-0-7851-8557-4',
    upc: '',
    diamondCode: 'NOV130730',
    ean: '9780785 185574 53499',
    issn: '',
    format: 'Trade Paperback',
    pageCount: 392,
    textObjects: [],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/47771',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/collection/47771/journey_into_mystery_by_kieron_gillen_the_complete_collection_trade_paperback?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: {
      resourceURI: 'http://gateway.marvel.com/v1/public/series/18043',
      name: 'Journey Into Mystery by Kieron Gillen: The Complete Collection (2014)',
    },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2014-06-18T00:00:00-0400' },
      { type: 'focDate', date: '2013-12-30T00:00:00-0500' },
    ],
    prices: [{ type: 'printPrice', price: 34.99 }],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available', extension: 'jpg' },
    images: [],
    creators: {
      available: 23,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/47771/creators',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/9628', name: 'Ulises Arreola', role: 'colorist' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/13309',
          name: 'Elizabeth Dismang Breitweiser',
          role: 'colorist',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/11579', name: 'Sunny Gho', role: 'colorist' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/13393',
          name: 'Jessica Kholinne',
          role: 'colorist',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13482', name: 'Ifansyah Noor', role: 'colorist' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/11487', name: 'Arif Prianto', role: 'colorist' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/10783', name: 'John Rauch', role: 'colorist' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/12991',
          name: 'Rachelle Rosenberg',
          role: 'colorist',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/128', name: 'Doug Braithwaite', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/9317', name: 'Richard Elson', role: 'penciler' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/10824',
          name: 'Whilce Portacio',
          role: 'penciler',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/969', name: 'Mitch Breitweiser', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/538', name: 'Jeffrey Huet', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/7183', name: 'Allen Martinez', role: 'inker' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/10172',
          name: 'Vc Clayton Cowles',
          role: 'letterer',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/8504',
          name: "Frank D'ARMATA",
          role: 'colorist (cover)',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/365',
          name: 'Pasqual Ferry',
          role: 'inker (cover)',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/8901', name: 'Kieron Gillen', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/418', name: 'Rob Rodi', role: 'writer' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/10785',
          name: 'Stephanie Hans',
          role: 'painter (cover)',
        },
      ],
      returned: 20,
    },
    characters: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/47771/characters',
      items: [],
      returned: 0,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/47771/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/107819',
          name: 'cover from Journey Into Mystery by Kieron Gillen: The Complete Collection (2014)',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/107820',
          name: 'story from Journey Into Mystery by Kieron Gillen: The Complete Collection (2014)',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/47771/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 92794,
    digitalId: 0,
    title: 'Heroes Return (2021) #1',
    issueNumber: 1,
    variantDescription: '',
    description: null,
    modified: '2021-06-21T03:14:31-0400',
    isbn: '',
    upc: '75960620076400111',
    diamondCode: 'APR210712',
    ean: '',
    issn: '',
    format: 'Comic',
    pageCount: 40,
    textObjects: [],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/92794',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/issue/92794/heroes_return_2021_1?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/HEROES-RETURN-1-1/digital-comic/56896?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: { resourceURI: 'http://gateway.marvel.com/v1/public/series/31709', name: 'Heroes Return (2021)' },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2021-06-23T00:00:00-0400' },
      { type: 'focDate', date: '2021-05-31T00:00:00-0400' },
    ],
    prices: [{ type: 'printPrice', price: 5.99 }],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/6/30/60cd0f3d91707', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/6/30/60cd0f3d91707', extension: 'jpg' }],
    creators: {
      available: 8,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92794/creators',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/11463', name: 'Jason Aaron', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/2133', name: 'Tom Brevoort', role: 'editor' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/11579',
          name: 'Sunny Gho',
          role: 'colorist (cover)',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/649', name: 'Ed Mcguinness', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/454', name: 'Mark Morales', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12980', name: 'Vc Cory Petit', role: 'letterer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/10279', name: 'Matthew Wilson', role: 'colorist' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/758',
          name: 'Leinil Francis Yu',
          role: 'penciler (cover)',
        },
      ],
      returned: 8,
    },
    characters: {
      available: 1,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92794/characters',
      items: [{ resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009165', name: 'Avengers' }],
      returned: 1,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92794/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/206687',
          name: 'cover from Reborn Omega (2021) #1',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/206688',
          name: 'story from Reborn Omega (2021) #1',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92794/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 56069,
    digitalId: 40792,
    title: 'Deadpool (2015) #5',
    issueNumber: 5,
    variantDescription: '',
    description:
      'Deadpool knows who the imposter out to ruin him is! And he has the perfect bait to lure the baddie out...his innocent daughter, Ellie!',
    modified: '2021-06-20T09:03:48-0400',
    isbn: '',
    upc: '75960608332900511',
    diamondCode: 'NOV150895',
    ean: '',
    issn: '',
    format: 'Comic',
    pageCount: 32,
    textObjects: [
      {
        type: 'issue_solicit_text',
        language: 'en-us',
        text: 'Deadpool knows who the imposter out to ruin him is! And he has the perfect bait to lure the baddie out...his innocent daughter, Ellie!',
      },
    ],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/56069',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/issue/56069/deadpool_2015_5?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/Deadpool-5/digital-comic/40792?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'reader',
        url: 'http://marvel.com/digitalcomics/view.htm?iid=40792&utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'inAppLink',
        url: 'https://applink.marvel.com/issue/40792?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: { resourceURI: 'http://gateway.marvel.com/v1/public/series/20613', name: 'Deadpool (2015 - 2017)' },
    variants: [
      {
        resourceURI: 'http://gateway.marvel.com/v1/public/comics/59321',
        name: 'Deadpool (2015) #5 (Moore 2nd Printing Variant)',
      },
    ],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2016-01-06T00:00:00-0500' },
      { type: 'focDate', date: '2015-12-21T00:00:00-0500' },
      { type: 'unlimitedDate', date: '2016-07-04T00:00:00-0400' },
      { type: 'digitalPurchaseDate', date: '2016-01-06T00:00:00-0500' },
    ],
    prices: [
      { type: 'printPrice', price: 3.99 },
      { type: 'digitalPurchasePrice', price: 3.99 },
    ],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/4/20/5681b9a78f417', extension: 'jpg' },
    images: [
      { path: 'http://i.annihil.us/u/prod/marvel/i/mg/4/20/5681b9a78f417', extension: 'jpg' },
      { path: 'http://i.annihil.us/u/prod/marvel/i/mg/3/d0/567aee1858063', extension: 'jpg' },
    ],
    creators: {
      available: 3,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/56069/creators',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/11680', name: 'Gerry Duggan', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/942', name: 'Mike Hawthorne', role: 'artist' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/9586',
          name: 'Tony Moore',
          role: 'penciller (cover)',
        },
      ],
      returned: 3,
    },
    characters: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/56069/characters',
      items: [],
      returned: 0,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/56069/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/123101',
          name: 'cover from Deadpool (2015) #5',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/123102',
          name: 'story from Deadpool (2015) #5',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/56069/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 36424,
    digitalId: 21458,
    title: 'X-Men Legacy (2008) #250',
    issueNumber: 250,
    variantDescription: '',
    description:
      'The X-Men have escaped the Age of X and returned to Utopia, but something sinister followed them back. Upon discovering that this new evil has been set loose, Rogue and Magneto round up a team to hunt it down.',
    modified: '2021-06-20T09:03:48-0400',
    isbn: '',
    upc: '5960601772-25011',
    diamondCode: '',
    ean: '',
    issn: '1941-2150',
    format: 'Comic',
    pageCount: 64,
    textObjects: [
      {
        type: 'issue_solicit_text',
        language: 'en-us',
        text: '"AGE OF X: AFTERMATH!" The X-Men have escaped the AGE OF X and returned to Utopia...unaware that something sinister followed them back. Upon discovering that this new evil has been loosed into the world, Rogue and Magneto round up a team of X-Men to hunt it down. But is this motley new crew of X-Men prepared for what awaits them?',
      },
      {
        type: 'issue_preview_text',
        language: 'en-us',
        text: 'The X-Men have escaped the Age of X and returned to Utopia, but something sinister followed them back. Upon discovering that this new evil has been set loose, Rogue and Magneto round up a team to hunt it down.',
      },
    ],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/36424',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/issue/36424/x-men_legacy_2008_250?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/X-Men-Legacy-250/digital-comic/21458?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'reader',
        url: 'http://marvel.com/digitalcomics/view.htm?iid=21458&utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'inAppLink',
        url: 'https://applink.marvel.com/issue/21458?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: { resourceURI: 'http://gateway.marvel.com/v1/public/series/3754', name: 'X-Men Legacy (2008 - 2012)' },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2011-06-08T00:00:00-0400' },
      { type: 'focDate', date: '2011-05-16T00:00:00-0400' },
      { type: 'unlimitedDate', date: '2012-12-29T00:00:00-0500' },
      { type: 'digitalPurchaseDate', date: '2012-10-30T00:00:00-0400' },
    ],
    prices: [
      { type: 'printPrice', price: 4.99 },
      { type: 'digitalPurchasePrice', price: 1.99 },
    ],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/c/10/51a4e4df338ac', extension: 'jpg' },
    images: [
      { path: 'http://i.annihil.us/u/prod/marvel/i/mg/c/10/51a4e4df338ac', extension: 'jpg' },
      { path: 'http://i.annihil.us/u/prod/marvel/i/mg/9/40/4dd3d371b7f60', extension: 'jpg' },
      { path: 'http://i.annihil.us/u/prod/marvel/i/mg/8/e0/4dd3d34b8d041', extension: 'jpg' },
      { path: 'http://i.annihil.us/u/prod/marvel/i/mg/9/10/4dd3d30e502e9', extension: 'jpg' },
      { path: 'http://i.annihil.us/u/prod/marvel/i/mg/8/c0/4dd3d2e0433a6', extension: 'jpg' },
      { path: 'http://i.annihil.us/u/prod/marvel/i/mg/b/c0/4dd3d2a33d19a', extension: 'jpg' },
      { path: 'http://i.annihil.us/u/prod/marvel/i/mg/f/10/4dd3d26acc3d7', extension: 'jpg' },
      { path: 'http://i.annihil.us/u/prod/marvel/i/mg/3/a0/4dd3d23397662', extension: 'jpg' },
      { path: 'http://i.annihil.us/u/prod/marvel/i/mg/c/80/4d88cf41a4b8b', extension: 'jpg' },
    ],
    creators: {
      available: 9,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/36424/creators',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/366', name: 'Mike Carey', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/872', name: 'Marte Gracia', role: 'colorist' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/582', name: 'Brian Reber', role: 'colorist' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/11737', name: 'Daniel Ketchum', role: 'editor' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/4981', name: 'Steve Kurth', role: 'penciller' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/1103', name: 'Khoi Pham', role: 'penciller' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/616', name: 'Jay Leisten', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/527', name: 'Tom Palmer', role: 'letterer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/361', name: 'Cory Petit', role: 'letterer' },
      ],
      returned: 9,
    },
    characters: {
      available: 9,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/36424/characters',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009313', name: 'Gambit' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009337', name: 'Havok' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009399', name: 'Legion' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009417', name: 'Magneto' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009499', name: 'Polaris' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009504', name: 'Professor X' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009430', name: 'Rachel Grey' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009546', name: 'Rogue' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009726', name: 'X-Men' },
      ],
      returned: 9,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/36424/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/80878',
          name: 'X-MEN LEGACY (2008) #250',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/80879',
          name: 'X-Men Legacy (2008) #250',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/36424/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 95052,
    digitalId: 0,
    title: "Marvel's Voices: Pride (2021) #1",
    issueNumber: 1,
    variantDescription: '',
    description: null,
    modified: '2021-06-17T11:05:07-0400',
    isbn: '',
    upc: '75960620185300111',
    diamondCode: 'APR210808',
    ean: '',
    issn: '',
    format: 'Comic',
    pageCount: 88,
    textObjects: [],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/95052',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/issue/95052/marvels_voices_pride_2021_1?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/MARVEL-S-VOICES-PRIDE-1-1/digital-comic/56901?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: { resourceURI: 'http://gateway.marvel.com/v1/public/series/32375', name: "Marvel's Voices: Pride (2021)" },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2021-06-23T00:00:00-0400' },
      { type: 'focDate', date: '2021-05-31T00:00:00-0400' },
    ],
    prices: [{ type: 'printPrice', price: 9.99 }],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/6/40/60cd0f40b0989', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/6/40/60cd0f40b0989', extension: 'jpg' }],
    creators: {
      available: 35,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/95052/creators',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/14282',
          name: 'Claudia Aguirre',
          role: 'penciler',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/11575', name: 'Kris Anka', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12998', name: 'Jan Bazaldua', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/14271', name: 'Samantha Dodge', role: 'penciler' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/13162',
          name: 'Erick Arciniega',
          role: 'colorist',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/12744',
          name: 'Tamra Bonvillain',
          role: 'colorist',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/8653', name: 'Jacopo Camagni', role: 'colorist' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13021', name: 'David Curiel', role: 'colorist' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/12990',
          name: 'Paulina Ganucheau',
          role: 'colorist',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13590', name: 'Vita Ayala', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/14184', name: 'Terry Blas', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/14148', name: 'Crystal Frasier', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/8901', name: 'Kieron Gillen', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/358', name: 'Allan Heinberg', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13200', name: 'Sarah Brunstad', role: 'editor' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13526', name: 'Derek Charm', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/357', name: 'Jim Cheung', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/14192', name: 'Joanna Estep', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12426', name: 'Javier Garron', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/14264', name: 'Jennifer Hickman', role: 'inker' },
      ],
      returned: 20,
    },
    characters: {
      available: 18,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/95052/characters',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1017574', name: 'Angela (Aldrif Odinsdottir)' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009185', name: 'Black Cat' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011001', name: 'Daken' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009271', name: 'Destiny' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009343', name: 'Hercules' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009355', name: 'Hulkling' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009362', name: 'Iceman' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011386', name: 'Karma' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010752', name: 'Karolina Dean ' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010450', name: 'Lightspeed' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009427', name: 'Marvel Boy' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009465', name: 'Mystique' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010746', name: 'Nico Minoru' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009476', name: 'Northstar' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011030', name: 'Prodigy' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009542', name: 'Rictor' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010833', name: 'Speed' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009714', name: 'Wiccan' },
      ],
      returned: 18,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/95052/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/211232',
          name: "cover from Marvel's Voices: Pride (2021) #1",
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/211233',
          name: "story from Marvel's Voices: Pride (2021) #1",
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/95052/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 12412,
    digitalId: 1505,
    title: 'Avengers Forever (1998) #9',
    issueNumber: 9,
    variantDescription: '',
    description:
      "The most unlikely teamup ever...it's Kang, the Supreme Intelligence and Rick Jone to save the universe!",
    modified: '2021-06-16T21:30:21-0400',
    isbn: '',
    upc: '',
    diamondCode: '',
    ean: '',
    issn: '',
    format: 'Comic',
    pageCount: 0,
    textObjects: [
      {
        type: 'issue_solicit_text',
        language: 'en-us',
        text: "The most unlikely teamup ever...it's Kang, the Supreme Intelligence and Rick Jones to save the universe!",
      },
      {
        type: 'issue_preview_text',
        language: 'en-us',
        text: "The most unlikely teamup ever...it's Kang, the Supreme Intelligence and Rick Jone to save the universe!",
      },
    ],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/12412',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/issue/12412/avengers_forever_1998_9?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/Avengers-Forever-9/digital-comic/1505?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'reader',
        url: 'http://marvel.com/digitalcomics/view.htm?iid=1505&utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'inAppLink',
        url: 'https://applink.marvel.com/issue/1505?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: { resourceURI: 'http://gateway.marvel.com/v1/public/series/2111', name: 'Avengers Forever (1998 - 2001)' },
    variants: [],
    collections: [
      {
        resourceURI: 'http://gateway.marvel.com/v1/public/comics/1033',
        name: 'Avengers Legends Vol. I: Avengers Forever (Trade Paperback)',
      },
    ],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '1999-08-10T00:00:00-0400' },
      { type: 'focDate', date: '-0001-11-30T00:00:00-0500' },
      { type: 'unlimitedDate', date: '2007-11-13T00:00:00-0500' },
      { type: 'digitalPurchaseDate', date: '2011-07-05T00:00:00-0400' },
    ],
    prices: [
      { type: 'printPrice', price: 0 },
      { type: 'digitalPurchasePrice', price: 1.99 },
    ],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/6/b0/60d5e4168fb92', extension: 'jpg' },
    images: [
      { path: 'http://i.annihil.us/u/prod/marvel/i/mg/6/b0/60d5e4168fb92', extension: 'jpg' },
      { path: 'http://i.annihil.us/u/prod/marvel/i/mg/d/20/4bc47c7f39fd7', extension: 'jpg' },
    ],
    creators: {
      available: 12,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/12412/creators',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/2133', name: 'Tom Brevoort', role: 'editor' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/5075', name: 'Bobbie Chase', role: 'editor' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/375', name: 'Bob Harras', role: 'editor' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/4065', name: 'Gregg Schigiel', role: 'editor' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/1231', name: 'Kurt Busiek', role: 'writer' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/958', name: 'Roger Stern', role: 'writer' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/3603',
          name: 'Albert Deschesne',
          role: 'letterer',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/350',
          name: 'Richard Starkings',
          role: 'letterer',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/4401', name: 'Tony Kelly', role: 'colorist' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/4205', name: 'Steve Oliff', role: 'colorist' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/4402', name: 'Jesus Merino', role: 'inker' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/101',
          name: 'Carlos Pacheco',
          role: 'penciller (cover)',
        },
      ],
      returned: 12,
    },
    characters: {
      available: 11,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/12412/characters',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010354', name: 'Adam Warlock' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009220', name: 'Captain America' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009338', name: 'Hawkeye' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009343', name: 'Hercules' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009351', name: 'Hulk' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009368', name: 'Iron Man' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009384', name: 'Kang' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009562', name: 'Scarlet Witch' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010791', name: 'Sub-Mariner' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009662', name: 'Thing' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009664', name: 'Thor' },
      ],
      returned: 11,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/12412/stories',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/stories/26232', name: 'Cover #26232', type: 'cover' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/26233',
          name: 'Break: Reflections of the Conqueror',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/12412/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 92968,
    digitalId: 56409,
    title: 'King in Black: Spider-Man (2021) #1',
    issueNumber: 1,
    variantDescription: '',
    description: null,
    modified: '2021-06-16T20:51:28-0400',
    isbn: '',
    upc: '75960620088700111',
    diamondCode: 'JAN210532',
    ean: '',
    issn: '',
    format: 'Comic',
    pageCount: 40,
    textObjects: [],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/92968',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/issue/92968/king_in_black_spider-man_2021_1?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/KING-IN-BLACK-SPIDER-MAN-1-1/digital-comic/56409?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'reader',
        url: 'http://marvel.com/digitalcomics/view.htm?iid=56409&utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'inAppLink',
        url: 'https://applink.marvel.com/issue/56409?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: {
      resourceURI: 'http://gateway.marvel.com/v1/public/series/31788',
      name: 'King in Black: Spider-Man (2021)',
    },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2021-03-17T00:00:00-0400' },
      { type: 'focDate', date: '2021-02-22T00:00:00-0500' },
      { type: 'unlimitedDate', date: '2021-06-21T00:00:00-0400' },
      { type: 'digitalPurchaseDate', date: '2021-03-17T00:00:00-0400' },
    ],
    prices: [
      { type: 'printPrice', price: 4.99 },
      { type: 'digitalPurchasePrice', price: 4.99 },
    ],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/2/d0/60464e31801cc', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/2/d0/60464e31801cc', extension: 'jpg' }],
    creators: {
      available: 10,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92968/creators',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/11482',
          name: 'Jesus Aburtov',
          role: 'colorist (cover)',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/13225',
          name: 'Alberto Alburquerque',
          role: 'inker',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/13174',
          name: "Elisabetta D'AMICO",
          role: 'inker',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/13162',
          name: 'Erick Arciniega',
          role: 'colorist',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/12991',
          name: 'Rachelle Rosenberg',
          role: 'colorist',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/13141',
          name: 'Michele Bandini',
          role: 'penciler',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/5251',
          name: 'Vc Joe Caramagna',
          role: 'letterer',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/10355',
          name: 'Carlos Gomez',
          role: 'inker (cover)',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/12457',
          name: 'Edward Devin Lewis',
          role: 'editor',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13471', name: 'Jed Mackay', role: 'writer' },
      ],
      returned: 10,
    },
    characters: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92968/characters',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011376', name: 'Reptil' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009610', name: 'Spider-Man' },
      ],
      returned: 2,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92968/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/207026',
          name: 'cover from King in Black: Spider-Man (2021) #1',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/207027',
          name: 'story from King in Black: Spider-Man (2021) #1',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92968/events',
      items: [],
      returned: 0,
    },
  },
  {
    id: 92166,
    digitalId: 56391,
    title: 'Captain America Anniversary Tribute (2021) #1',
    issueNumber: 1,
    variantDescription: '',
    description: null,
    modified: '2021-06-16T20:25:11-0400',
    isbn: '',
    upc: '75960620050400111',
    diamondCode: 'JAN210611',
    ean: '',
    issn: '',
    format: 'Comic',
    pageCount: 56,
    textObjects: [],
    resourceURI: 'http://gateway.marvel.com/v1/public/comics/92166',
    urls: [
      {
        type: 'detail',
        url: 'http://marvel.com/comics/issue/92166/captain_america_anniversary_tribute_2021_1?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'purchase',
        url: 'http://comicstore.marvel.com/CAPTAIN-AMERICA-ANNIVERSARY-TRIBUTE-1-1/digital-comic/56391?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'reader',
        url: 'http://marvel.com/digitalcomics/view.htm?iid=56391&utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
      {
        type: 'inAppLink',
        url: 'https://applink.marvel.com/issue/56391?utm_campaign=apiRef&utm_source=07e3e205bebd46de31d15ee9a76d85c2',
      },
    ],
    series: {
      resourceURI: 'http://gateway.marvel.com/v1/public/series/31545',
      name: 'Captain America Anniversary Tribute (2021)',
    },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [
      { type: 'onsaleDate', date: '2021-03-17T00:00:00-0400' },
      { type: 'focDate', date: '2021-02-22T00:00:00-0500' },
      { type: 'unlimitedDate', date: '2021-06-21T00:00:00-0400' },
      { type: 'digitalPurchaseDate', date: '2021-03-17T00:00:00-0400' },
    ],
    prices: [
      { type: 'printPrice', price: 6.99 },
      { type: 'digitalPurchasePrice', price: 6.99 },
    ],
    thumbnail: { path: 'http://i.annihil.us/u/prod/marvel/i/mg/6/00/60464e360f2cb', extension: 'jpg' },
    images: [{ path: 'http://i.annihil.us/u/prod/marvel/i/mg/6/00/60464e360f2cb', extension: 'jpg' }],
    creators: {
      available: 60,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92166/creators',
      items: [
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/1004', name: 'Daniel Acuna', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/87', name: 'Mark Bagley', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13031', name: 'Juann Cabal', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12385', name: 'Carmen Carnero', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13106', name: 'Joshua Cassara', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/357', name: 'Jim Cheung', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/592', name: 'Rachel Dodson', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/13247', name: 'Rafael Fonteriz', role: 'inker' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/9018', name: 'Mahmud Asrar', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/506', name: 'Joe Bennett', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12765', name: 'Natacha Bustos', role: 'penciler' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/9998',
          name: 'Elena Casagrande',
          role: 'penciler',
        },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/162', name: 'John Cassaday', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/10445', name: 'Iban Coello', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/277', name: 'Terry Dodson', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/374', name: 'Steve Epting', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/12426', name: 'Javier Garron', role: 'penciler' },
        { resourceURI: 'http://gateway.marvel.com/v1/public/creators/2133', name: 'Tom Brevoort', role: 'editor' },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/5251',
          name: 'Vc Joe Caramagna',
          role: 'letterer',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/creators/8504',
          name: "Frank D'ARMATA",
          role: 'colorist (cover)',
        },
      ],
      returned: 20,
    },
    characters: {
      available: 1,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92166/characters',
      items: [{ resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009220', name: 'Captain America' }],
      returned: 1,
    },
    stories: {
      available: 2,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92166/stories',
      items: [
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/205416',
          name: 'cover from new series (2021) #1',
          type: 'cover',
        },
        {
          resourceURI: 'http://gateway.marvel.com/v1/public/stories/205417',
          name: 'story from new series (2021) #1',
          type: 'interiorStory',
        },
      ],
      returned: 2,
    },
    events: {
      available: 0,
      collectionURI: 'http://gateway.marvel.com/v1/public/comics/92166/events',
      items: [],
      returned: 0,
    },
  },
];
